### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Arch23-tech** [Pandarix/BushyFlowers#10]
Hello there 👋 

Before I download the mod I need a basic knowledge about the roadmap....

I like to know if the developer has further plan to update the mod to distant future minecraft versions..!

Because it affects the worldgen, so without it, our worlds (maps) will be corrupted forever.

**Comment by Pandarix** [comment]
Hi, thank you for your interest in my mod!
I will be totally honest with you:
I am a university student, so the spare time I can invest in mods is determined by my tasks.
For example, Better Archeology, another mod by me (which is a whole lot bigger and complex code-wise) will get an 1.21 update the next week's because I was caught up with exams and my Erasmus year.
However, I am always highly determined to maintain and improve my projects, learn new stuff and create new things.
So if your time-window accommodates for a little time for updates in comparison to big modding groups then yes, totally! :)

**Comment by Arch23-tech** [comment]
That's nice 
I also using your other mod (Better archeology) which I prefer it on top most other mods that adds dungeons and structures to the game.

Thank you for your mods and efforts  🙏 .
